### ISSUE TITLE
Why shows error "Timeout value connect was <object object at...."

### ISSUE THREAD

**Issue by jiangaq** [ranjan-mohanty/vfs-appointment-bot#20] opened 2023-10-12 16:04 UTC
Timeout value connect was <object object at 0x11008df20>, but it must be an int, float or None.. Please check the logs for more details

**Comment by naXa777** [comment] 2023-10-26 16:19
Is it a duplicate of #15? See solution there.

**Closed as completed** 2024-04-27 00:51 UTC
